### ISSUE TITLE
Could i ask a few questions about the training result?

### ISSUE THREAD

**Issue by StellarOdys2ey** [OoDBag/RISE#5]
I have run the code in VLCS dataset successfully and got several test accuracy in each domain, but after that how can I get a final result in this dataset? By calculating the weighted average accuracy of these four different domains or some other methods like a simple average of those test accuracy? It seems the result higher a lot than that showed in paper(81.7%) when I calculated in the weighted average way, which makes me a little confused.

**Comment by OoDBag** [comment]
Hi, thanks for your questions. The results presented are derived by averaging the test accuracy across each domain and then averaging those numbers across three different seeds. It's important to note that the term "test accuracy" refers specifically to the accuracy on the test set that corresponds to the best validation performance, rather than the highest test accuracy observed. Let me know if you need more information.
